### ISSUE TITLE
GDBM saves files in ASCII-8BIT, causes problems with UTF-8

### ISSUE THREAD

**Issue by KelseyDH** [presidentbeef/ffi-gdbm#3]
Hi there,

I was trying to follow this general [guide on scraping](http://ngauthier.com/2014/06/scraping-the-web-with-ruby.html), and had gotten everything working until I tried using this gem to dump JSON data to it.

After a lot of investigation I realized the issue is due to GDBM saving files in ASCII format, while ruby now relies primarily on UTF-8 encoding.

This code below independently replicates the problem I'm encountering:

```ruby
#!/usr/bin/env ruby
# encoding: UTF-8
require 'gdbm'
require 'json'


# # Data Storage Formats
testdb = GDBM.new("test.db")       # GDBM file
dump   = {}                        # in memory

# # Test Data
str    = '√'                       # #<Encoding:UTF-8>



# # stays UTF-8
puts "-------Without GDBM:"
str.encoding                       # => #<Encoding:UTF-8>
dump[str] = JSON.dump(str)
puts dump[str].encoding            # => #<Encoding:UTF-8>


# # GDBM saves to ASCII-8BIT
puts "-------With GDBM:"
str.encoding                       # => #<Encoding:UTF-8>
testdb[str] = JSON.dump(str)
puts testdb[str].encoding          # => #<Encoding:ASCII-8BIT>

JSON.load(testdb[str])             # `parse': 795: unexpected token at '"?' (JSON::ParserError)


```

At the end you can see how the incorrect encoding will trigger an error when the text being parsed has UTF-8 characters.

Is there a way to have `GDBM` play nice with `UTF-8`?

**Comment by presidentbeef** [comment]
Hi Kelsey,

Are you using `ffi-gdbm` or just the regular `gdbm` that comes with Ruby?

**Comment by presidentbeef** [comment]
I'm not sure this is actually a problem with this library or if it's a problem with JRuby's JSON parser, since running this on MRI (ruby 2.3.0p0) also shows GDBM converting it to ASCII-8BIT but it parses. Perhaps there's some conversion going on inside of the JSON library.

**Comment by presidentbeef** [comment]
Okay, looks like `ffi-gdbm` is losing information somewhere.

Testing with this:
```ruby
require 'gdbm'
require 'json'

# # Data Storage Formats
testdb = GDBM.new("test.db")       # GDBM file

# # Test Data
str    = '√'                       # #<Encoding:UTF-8>

puts "-------Without GDBM:"
p JSON.dump(str)

puts "-------With GDBM:"
testdb[str] = JSON.dump(str)
p testdb[str]
```
With MRI 2.3.0:
```
-------Without GDBM:
"\"√\""
-------With GDBM:
"\"\xE2\x88\x9A\""
```

With JRuby:
```
-------Without GDBM:
"\"√\""
-------With GDBM:
"\"\xE2\x88"
```
Clearly missing some bytes there. I have a theory...testing now...

**Comment by presidentbeef** [comment]
Okay, I've pushed version 1.3.1 which should fix this.

Thank you for reporting!

**Comment by KelseyDH** [comment]
@presidentbeef  Thank you for fixing this so promptly!  I notice GDBM still saves to ASCII-8BIT, but it appears that I no longer have an exception from the conversion so I guess this matter is fixed.

Thanks again!

**Comment by presidentbeef** [comment]
@KelseyDH yes, it still ends up being ASCII-8BIT, but that is the same as Ruby's stdlib so I am considering it "correct" behavior.
