### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found: __gdbm_lock_file

### ISSUE THREAD

**Issue by KelseyDH** [presidentbeef/ffi-gdbm#5]
I'm getting this odd error now when I try to use the GDBM gem.  The gem used to work.  Now when I invoke the GDBM gem I get this error (I get it across many different versions of ruby):

```
dyld: lazy symbol binding failed: Symbol not found: __gdbm_lock_file
  Referenced from: /usr/local/lib/libgdbm.dylib
  Expected in: flat namespace

dyld: Symbol not found: __gdbm_lock_file
  Referenced from: /usr/local/lib/libgdbm.dylib
  Expected in: flat namespace
```

I've tried numerous ruby versions and installing/uninstalling GDBM from Brew.  

The only major thing I can think has changed is that I'm now running on OSX El Capitan 10.11.6.  Or that I somehow made a change to my config or PATH files that could have brought this on.  

My GDBM Brew installation is at `/usr/local/Cellar/gdbm/1.12`

**Comment by presidentbeef** [comment]
Hmm. I'm still on Yosemite but installing gdbm 1.12 with brew worked fine. It's possible the El Capitan package has issues.

Can you ensure `ls -l /usr/local/lib/libgdbm*` is pointing at the correct gdbm install? I see three files: `libgdbm.4.dylib`, `libgdbm.a`, and `libgdbm.dylib`.

**Comment by KelseyDH** [comment]
I get this output, which appears to be linking the files correctly to the Brew installation.

```
lrwxr-xr-x  1 kelsey  admin  39 27 Sep 19:56 /usr/local/lib/libgdbm.4.dylib -> ../Cellar/gdbm/1.12/lib/libgdbm.4.dylib
lrwxr-xr-x  1 kelsey  admin  33 27 Sep 19:56 /usr/local/lib/libgdbm.a -> ../Cellar/gdbm/1.12/lib/libgdbm.a
lrwxr-xr-x  1 kelsey  admin  37 27 Sep 19:56 /usr/local/lib/libgdbm.dylib -> ../Cellar/gdbm/1.12/lib/libgdbm.dylib
```

**Comment by KelseyDH** [comment]
Also GDBM still works when I invoke it manually from the command line (e.g. `gdbm_load`).

**Comment by presidentbeef** [comment]
I get exactly the same symlinks on my machine. I'm pretty mystified.

You are seeing the error with just `require "gdbm"`? Using JRuby?

**Comment by KelseyDH** [comment]
I'm using MRI, but I tried it with `jruby-1.7.21` via Rbenv and it still fails (with the same error message) if I execute code such as:

```
#!/usr/bin/env ruby
# encoding: UTF-8
require 'gdbm'

puts "test" # this shows up
testdb = GDBM.new("foo.db") # this fails
``` 
As you can see `require` works.  GDBM doesn't crash until you do something like `GDBM.new("foo.db")`

**Comment by presidentbeef** [comment]
Ah, okay. I see that now too.

In that case I believe this is due to the new version of gdbm (`1.12`) which was released a few months ago.

**Comment by presidentbeef** [comment]
This is not happening on Linux.

```
jruby-9.1.5.0 :001 > require 'gdbm'
 => true 
jruby-9.1.5.0 :002 > GDBM::VERSION
 => "GDBM version 1.12. 16/05/2016 (built Sep 30 2016 10:05:04)" 
jruby-9.1.5.0 :003 > GDBM.new "blah"
 => #<GDBM:0x3315d2d7 @file=#<FFI::Pointer address=0x7f1c48734200
```

**Comment by KelseyDH** [comment]
Interesting, someone has confirmed this error happens in [macSierra too](http://stackoverflow.com/questions/39760232/dyld-lazy-symbol-binding-failed-symbol-not-found-gdbm-lock-file-error-with/39783418#39783418).

**Comment by presidentbeef** [comment]
I believe this is a problem related to homebrew. I downloaded gdbm's [official release](http://puszcza.gnu.org.ua/projects/gdbm), compiled, installed, and it worked fine.

**Comment by presidentbeef** [comment]
I have tried everything I can think of. Even `./configure && make install` from homebrew's cached source from `brew install gdbm --build-from-source` **works**. But letting homebrew do it itself does not. I notice the lib files are not the same size as the manual build and one is missing (`libgdbm.la`), although the missing file does not appear to matter in this case.

I suggest filing an issue with homebrew or just manually installing gdbm since it's an easy library to install.

**Comment by KelseyDH** [comment]
Ok, that makes sense.   I'll look into doing that. Thanks for looking into this.
